name: Build
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt-hotspot
      - name: Compile source
        run: mvn clean compile
      - name: Run tests
        run: mvn test
      - name: Generate test coverage report
        run: mvn jacoco:report
      - name: Try to upload the coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          verbose: false
      - name: Package plugin .JAR
        run: mvn package
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: Plugin files
          path: "${{ github.workspace }}/target/Day*.jar"
          if-no-files-found: error
